apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ace-accp
  name: ace-accp-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ace-accp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ace-accp
    spec:
      containers:
      - image: {{  printf "%s/eod20-ace:%s" .Values.imageRepo .Values.aceAccp.tag}}
        name: myace
        resources: {}
        env:
        - name: LICENSE
          value: accept
        - name: ACE_SERVER_NAME
          value: K8SSERVER
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
status: {}
