apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: inputmsg-collection-cj
  namespace: eod20
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: inputmsg-collection-cj
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: jasperlanda/eod20-inputmsg-collection
            name: inputmsg-collection
            resources: {}
            volumeMounts:
            - name: config
              mountPath: "/config"
          restartPolicy: Never
          volumes:
          - name: config
            secret:
              secretName: inputmsg-collection-secret
  schedule: '*/10 * * * *'
status: {}