apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: inputmsg-collection-cj
  namespace: eod20
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: inputmsg-collection-cj
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: jasperlanda/eod20-inputmsg-collection
            name: inputmsg-collection
            resources: {}
            volumeMounts:
            - name: ace-config
              mountPath: "/ace-config"
            - name: api-users
              mountPath: "/api-user"
          restartPolicy: Never
          volumes:
          - name: ace-config
            secret:
              secretName: ace-accp-config
          - name: api-users
            secret:
              secretName: inputmsg-api-users-secret
  schedule: '*/5 * * * *'
status: {}