apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: inputmsg-api
  name: inputmsg-api
  namespace: eod20
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inputmsg-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: inputmsg-api
    spec:
      containers:
      - image: jasperlanda/eod20-inputmsg-api:latest
        name: inputmsg-api
        volumeMounts:
        - name: users
          mountPath: "/users"
        - name: data
          mountPath: "/data"
      volumes:
      - name: users
        secret:
          secretName: inputmsg-api-users-secret
      - name: data
        persistentVolumeClaim:
          claimName: inputmsg-api-pvc
      imagePullSecrets:
      - name: regcred
status: {}