apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-pod
  name: test-pod
  namespace: eod20
spec:
  containers:
  - image: jasperlanda/eod20-inputmsg-collection
    name: test-pod
    resources: {}
    volumeMounts:
    - name: config
      mountPath: "/config"
  restartPolicy: OnFailure
  volumes:
  - name: config
    secret:
      secretName: inputmsg-collection-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}