apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: inputmsg-collection-cj
spec:
  jobTemplate:
    metadata:
      name: inputmsg-collection-cj
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: {{  printf "%s/eod20-inputmsg-collection:%s" .Values.imageRepo .Values.inputMsgCollection.tag }}
            name: inputmsg-collection
            resources: {}
            env:
            - name: EOD20_INPUTMSGCOLL_MOUNT_PATH
              value: "/"
            volumeMounts:
            - name: ace-config
              mountPath: "/ace-config"
            - name: api-users
              mountPath: "/api-user"
          restartPolicy: Never
          volumes:
          - name: ace-config
            secret:
              secretName: ace-accp-config
          - name: api-users
            secret:
              secretName: inputmsg-api-users-secret
          imagePullSecrets:
          - name: {{ .Values.imagePullSecret }}
  schedule: {{ .Values.inputMsgCollection.schedule | quote }}
status: {}