apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: inputmsg-api
  name: inputmsg-api
spec:
  replicas: {{ .Values.inputMsgApi.replicas }}
  selector:
    matchLabels:
      app: inputmsg-api
  strategy: {}
  template:
    metadata:
      labels:
        app: inputmsg-api
    spec:
      containers:
      - image: {{  printf "%s/eod20-inputmsg-api:%s" .Values.imageRepo .Values.inputMsgApi.tag }}
        name: inputmsg-api
        env:
        - name: EOD20_INPUTMSGAPI_MOUNT_PATH
          value: "/"
        volumeMounts:
        - name: users
          mountPath: "/users"
        - name: data
          mountPath: "/data"
      volumes:
      - name: users
        secret:
          secretName: inputmsg-api-users
      - name: data
        persistentVolumeClaim:
          claimName: inputmsg-api-pvc
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
status: {}