apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: inputmsg-api-pvc
 labels:
   app: inputmsg-api
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: {{ .Values.inputMsgApi.storage }}
 storageClassName: ibmc-file-retain-gold