apiVersion: v1
kind: Service
metadata:
  name: stub-endpoint-svc
  labels:
    app: stub
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
    name: "8081"
  selector:
    app: stub
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}