apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: stub
  name: stub-endpoint
spec:
  replicas: {{ .Values.stubEndpoint.replicas }}
  selector:
    matchLabels:
      app: stub
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stub
    spec:
      containers:
      - image: {{  printf "%s/eod20-stub-endpoint:%s" .Values.imageRepo .Values.stubEndpoint.tag }}
        name: stub-endpoint
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
status: {}