apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stub-endpoint-ingress
  annotations: {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  tls:
  - secretName: {{ .Values.tlsSecret }}
    hosts:
    - {{ printf "stub.%s" .Values.ibmCloudKsHost }}
  rules:
  - host: {{ printf "stub.%s" .Values.ibmCloudKsHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stub-endpoint-svc
            port:
              number: 8081
