apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: unit-test-api-pvc
 labels:
   app: unit-test-api
spec:
 accessModes:
   - ReadWriteMany
 resources:
   requests:
     storage: {{ .Values.unitTestApi.storage }}
 storageClassName: {{ .Values.unitTestApi.storageClassName }}