apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unit-test-api-ingress
  annotations: {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  tls:
  - secretName: {{ .Values.ingress.tlsSecret }}
    hosts:
    - {{ printf "unit-test-api.%s" .Values.ibmCloudKsHost }}
  rules:
  - host: {{ printf "unit-test-api.%s" .Values.ibmCloudKsHost }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: unit-test-api-svc
            port:
              number: 8082
