apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: unit-test-api
  name: unit-test-api
spec:
  replicas: {{ .Values.unitTestApi.replicas }}
  selector:
    matchLabels:
      app: unit-test-api
  strategy: {}
  template:
    metadata:
      labels:
        app: unit-test-api
    spec:
      containers:
      - image: {{  printf "%s/eod20-unit-test-api:%s" .Values.imageRepo .Values.unitTestApi.tag }}
        name: unit-test-api
        env:
        - name: EOD20_UNITTESTAPI_MOUNT_PATH
          value: "/"
        volumeMounts:
        - name: users
          mountPath: "/users"
        - name: ace-config
          mountPath: "/ace-config"
        - name: data
          mountPath: "/data"
      volumes:
      - name: users
        secret:
          secretName: unit-test-api-users
      - name: ace-config
        secret:
          secretName: ace-test-config
      - name: data
        persistentVolumeClaim:
          claimName: unit-test-api-pvc
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
status: {}