apiVersion: v1
kind: Service
metadata:
  name: unit-test-api-svc
  labels:
    app: unit-test-api
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
    name: "8082"
  selector:
    app: unit-test-api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}