apiVersion: v1
data:
  host: YWNlLXN2Yy5hY2U=
  https: ZmFsc2U=
  port: NzYwMA==
  pw: YWRtaW4x
  user: YWRtaW4x
kind: Secret
metadata:
  creationTimestamp: null
  name: inputmsg-collection-secret
  namespace: eod20
