ibmCloudKsHost: eod20-618dd4f5cf576582d05dea2fdbda72d6-0000.eu-de.containers.appdomain.cloud
tlsSecret: eod20-618dd4f5cf576582d05dea2fdbda72d6-0000

imageRepo: de.icr.io/landa

imagePullSecret: icr

ingress:
  annotations: 
    ingress.bluemix.net/redirect-to-https: "True"

# stub-endpoint docker image tag and replicas
stubEndpoint:
  tag: latest
  replicas: 1
 
# input-msg-api docker image tag, replicas, PVC size and basic auth config
inputMsgApi:
  tag: latest
  replicas: 3
  storageClassName: ibmc-file-retain-gold
  storage: 3Gi
  auth:
    user1: pw1
    user2: pw2

# unit-test-api docker image tag, replicas, PVC size and basic auth config
unitTestApi:
  tag: latest
  replicas: 3
  storageClassName: ibmc-file-retain-gold
  storage: 3Gi
  auth:
    user1: pw1
    user2: pw2

# input-msg-collection docker image tag and cronjob schedule
inputMsgCollection:
  tag: latest
  schedule: "*/3 * * * *"

# for ACE test and accp, specify the cluster-internal addres (for ACE on K8s, this is always equal to <service_name>:<namespace>), port, and an ACE user+pw  
aceTest:
  host: ace-test-svc.ace
  port: "7600"
  user: admin1
  pw: admin1
  
aceAccp:
  host: ace-accp-svc.ace
  port: "7600"
  user: admin1
  pw: admin1