apiVersion: v1
kind: Service
metadata:
  namespace: eod20
  name: stub-endpoint-svc
  labels:
    app: stub
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    name: "5000"
  selector:
    app: stub
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}